# Sample config file
# Commented entries are the defaults
# Uncomment and change to override

# Logging level (just stderr output at the moment)
# Logs only this level of message and above through the log facility
# loglevel: CRITICAL

# The wordpress export xml (WPXR) filename.
# wpxr_file: wpxr/wpxr.xml

# The target directory where all output is saved.
# build_dir: build


# Output extension
# target_extension: md

# Subdir of target dir for the content
# content_dir: content

# Item types we don't want to keep
# item_type_filter:
#  - attachment
#  - custom_css
#  - flamingo_contact
#  - flamingo_inbound
#  - nav_menu_item
#  - wp_block
#  - wpcf7_contact_form

# Prevent page output for any field:value in the result tree.
# Note as an exception to the commented entries are defaults, for this
# entry the defaults is to have no filter
# item_field_filter:
#  wp_status: draft

# Ditto only with a list of possible values to filter out
# item_field_list_filter:
#   categories:
#     - uncategorized

# Remove fields we don't want in final output, but do during processing
# final_remove_fields:
#   - parent

# Don't emit wp_id in output files
# no_output_wp_id: true

# Replace certain patterns in content
# Currently has no default, the comment is an example
# content_replace: { "<sub>(.*?)</sub>": '{{% sub %}}\1{{% /sub %}}' }

# Remove single values we don't want, for a given field  (list of maps)
# remove_field_values:
#   - aliases: /

# Options for converting HTML content to Markdown using markdownify
# markdownify:
#   heading_style: ATX
#   strip: ["script"]

# Instead of login name use display name in Hugo author per-page metadata
# use_author_display_name_in_metadata: True

# For items of wp:post_type page keep the page hierarchy
# (creates a directory structure to match the exiting page hierarchy)
# keep_page_hierarchy: True

# Config file containing data models for converting the
# WPXR file to desired static generator
# May be yaml or toml
# data_models: hugo_data_model.yaml
