# Sample config file
# Commented entries are the defaults
# Uncomment and change to override

# Logging level (just stderr output at the moment)
# Logs only this level of message and above through the log facility
# loglevel: ERROR

# The wordpress export xml (WPXR) filename.
# wpxr_file: wpxr/wpxr.xml

# The target directory where all output is saved.
# build_dir: build

# Subdir of target dir for the content
# content_dir: content

# Download image files from content bodies
# download_content_images: false

# Relative path to your WordPress images
# e.g. /wp-content/uploads would create a match for
# an image in you WPXR with a URL such as
# https://www.example.com/wp-content/uploads/2021/01/an-image-file.png
# If www.example.com were the site's base URL.
# image_origin_rel_url: /wp-content/uploads

# Where to find your WordPress images on your local filesystem
# Assumes you have copied them to your local system, for example
# using rclone, scp, or other network copy tool, or that you have
# download_content_images set to true (which will download to this location)
# If empty wpxr-to-static will not try to move the image
# files into the site's build (output) folder
# image_origin_local_path:

# Where in the output (build) folder for the site
# to put the files (maintains the same file structure
# as the source except that the site baseURL and WP relative path are
# removed.
# image_destination_path: static/images

# relative path to WorldPress images when live:
# image_rel_url: /images

# Output extension
# target_extension: md

# Subdir of target dir for the content
# content_dir: content

# Item types we don't want to keep
# item_type_filter:
#  - attachment
#  - custom_css
#  - flamingo_contact
#  - flamingo_inbound
#  - nav_menu_item
#  - wp_block
#  - wpcf7_contact_form

# Prevent page output for any field:value in the result tree.
# Note as an exception to the commented entries are defaults, for this
# entry the defaults is to have no filter
# item_field_filter:
#  wp_status: draft

# Ditto only with a list of possible values to filter out
# item_field_list_filter:
#   categories:
#     - uncategorized

# Remove fields we don't want in final output, but do during processing
# final_remove_fields:
#   - _customize_changeset_uuid
#   - parent
#   - type

# Remove fields we don't want in final output, using a regexp
# Default is not not filter fields by regexp
# regexp_remove_fields:
#   - "_oembed_.*"

# Don't emit wp_id in output files
# no_output_wp_id: true

# Replace certain patterns in a field's value
# Currently has no default, the comment is an example
# fields_value_replace:
# content:
#   "<sub>(.*?)</sub>": '{{< sub >}}\1{{< /sub >}}'
#   "<pre.*?><code.*?>(.*?)</code></pre>": '{{< highlight Javascript >}}\1{{< /highlight >}}'
# type:
#  "post": "posts" # Required for hugo-geekdoc theme to treat blog pages as blog posts

# Remove single values we don't want, for a given field  (list of maps)
# remove_field_values:
#   - aliases: /

# Options for converting HTML content to Markdown using markdownify
# markdownify:
#   heading_style: ATX
#   strip: ["script"]

# Instead of login name use display name in Hugo author per-page metadata
# use_author_display_name_in_metadata: True

# For items of wp:post_type page keep the page hierarchy
# (creates a directory structure to match the exiting page hierarchy)
# keep_page_hierarchy: True

# Config file containing data models for converting the
# WPXR file to desired static generator
# May be yaml or toml
# data_models: hugo_data_model.yaml
